Removed Validator > Bank POST/PATCH endpoints
thenewboston-developers/dotnetcore-sdk pull request #86
Opened 2021-01-14 08:43 UTC by tomijaga

#80 #85 
I removed only the post/patch endpoints

>  BankBlockServices
  ~BankConfirmationServices~
  ~ConnectedBankService~
  ConnectionRequestServices
  UpgradeRequestService

the ones crossed out are the get endpoints

2021-01-14 10:15 UTC, Mirch requested changes
Almost done, but they also need to be removed from the Bank node :) there are some POST endpoints in there as well.

2021-01-15 09:19 UTC, tomijaga commented
Removed all Bank > Validator  Post/Patch endpoints

>BankConfirmationBlockService
ConnectionRequestServices
InvalidBlockService
UpgradeNoticeService
ValidatorConfirmationServices

2021-01-17 18:56 UTC, Mirch requested changes

2021-01-17 18:56 UTC, Mirch commented on src/Thenewboston.Tests/Bank/Api/InvalidBlockServiceTests.cs
> -                var invalidBankBlocks = await service.GetInvalidBankBlocksAsync();
This is a test for the GET endpoint. We need it.

2021-01-17 18:56 UTC, Mirch commented on src/Thenewboston/Bank/Api/IInvalidBlocksService.cs
> -        Task<PaginatedResponseModel<BankInvalidBlock>> GetInvalidBankBlocksAsync(int offset, int limit);
We need the GET endpoint.

2021-01-17 18:56 UTC, Mirch commented on src/Thenewboston/Bank/Api/InvalidBlocksService.cs
> -        {
Needed.

2021-01-18 08:18 UTC, Mirch approved these changes

2021-01-18 08:18 UTC, merged